import { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, BadgeDollarSign, Car, FileText, PhoneCall, RefreshCw, ShieldCheck, Trash2, UserCog, UsersRound } from 'lucide-react';
import { api } from '../api.js';
import StatusBadge from '../components/StatusBadge.jsx';

const tabs = [['overview','Command overview'],['activity','Audit stream'],['users','Accounts'],['personas','Personas'],['vehicles','Vehicles'],['calls','Calls'],['reports','Reports'],['market','Economy']];
const money = value => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value || 0);

export default function Admin({ user }) {
  const [data,setData]=useState({counts:{},users:[],characters:[],vehicles:[],calls:[],reports:[],orders:[],logs:[]});
  const [tab,setTab]=useState('overview'),[message,setMessage]=useState(''),[loading,setLoading]=useState(true);
  const load=useCallback(()=>api('/admin/overview').then(setData).catch(error=>setMessage(error.message)).finally(()=>setLoading(false)),[]);
  useEffect(()=>{load();},[load]);
  const onlineUsers=useMemo(()=>new Set(data.logs.filter(log=>log.action==='AUTH_LOGIN'&&Date.now()-new Date(log.created_at+'Z').getTime()<86400000).map(log=>log.user_id)).size,[data.logs]);
  async function mutate(path,options,success){setMessage('');try{await api(path,options);setMessage(success);await load();}catch(error){setMessage(error.message)}}
  const remove=(kind,id,label)=>{if(confirm(`Permanently remove ${label}? This action will be written to the audit log.`))mutate(`/admin/${kind}/${id}`,{method:'DELETE'},`${label} removed.`)};

  if(loading)return <div className="admin-loading"><ShieldCheck/><span>Decrypting administrator workspace…</span></div>;
  return <div><div className="page-heading"><div><p className="eyebrow">OWNER AUTHORITY · GRIZZLY CONTROL</p><h1>Administration center</h1><p>Global oversight, moderation, records control, and immutable activity intelligence.</p></div><button className="icon-button" onClick={load}><RefreshCw size={17}/> Sync everything</button></div>
    {message&&<div className="notice">{message}</div>}
    <section className="admin-identity"><div className="admin-seal"><ShieldCheck/></div><div><span>AUTHENTICATED OWNER</span><strong>{user.discord_username}</strong><small>Administrator clearance · All changes audited</small></div><div className="admin-live"><i/> COMMAND CHANNEL LIVE</div></section>
    <nav className="admin-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
    {tab==='overview'&&<Overview data={data} onlineUsers={onlineUsers} setTab={setTab}/>} 
    {tab==='activity'&&<ActivityStream logs={data.logs}/>} 
    {tab==='users'&&<Users data={data.users} currentUser={user} mutate={mutate}/>} 
    {tab==='personas'&&<Personas rows={data.characters} mutate={mutate} remove={remove}/>} 
    {tab==='vehicles'&&<Vehicles rows={data.vehicles} mutate={mutate} remove={remove}/>} 
    {tab==='calls'&&<Calls rows={data.calls} mutate={mutate} remove={remove}/>} 
    {tab==='reports'&&<Reports rows={data.reports} remove={remove}/>} 
    {tab==='market'&&<Economy users={data.users} orders={data.orders} mutate={mutate}/>} 
  </div>;
}

function Overview({data,onlineUsers,setTab}){const cards=[[UsersRound,'Accounts',data.counts.users,'users'],[UserCog,'Personas',data.counts.personas,'personas'],[Car,'Vehicles',data.counts.vehicles,'vehicles'],[PhoneCall,'Active calls',data.counts.activeCalls,'calls'],[FileText,'Reports',data.counts.reports,'reports'],[BadgeDollarSign,'Market orders',data.counts.orders,'market']];return <><div className="admin-metrics">{cards.map(([Icon,label,value,target])=><button key={label} onClick={()=>setTab(target)}><Icon/><span>{label}</span><strong>{value||0}</strong><small>Open management →</small></button>)}</div><div className="admin-overview-grid"><section className="panel"><div className="panel-heading"><div><span className="live-dot cyan"/> Latest network activity</div><small>ALL USERS</small></div><ActivityStream logs={data.logs.slice(0,12)} compact/></section><section className="panel admin-health"><div className="panel-heading"><div>System intelligence</div><small>LIVE</small></div><div><p><span>Users active today</span><strong>{onlineUsers}</strong></p><p><span>Record integrity</span><strong className="gain">AUDITED</strong></p><p><span>Database persistence</span><strong className="gain">ONLINE</strong></p><p><span>Unresolved incidents</span><strong>{data.counts.activeCalls||0}</strong></p></div></section></div></>}

function ActivityStream({logs,compact=false}){return <div className={`audit-stream ${compact?'compact':''}`}>{logs.length?logs.map(log=><article key={log.id}><div className="audit-icon"><Activity/></div><div><strong>{pretty(log.action)}</strong><span>{log.actor_name} · {log.entity_type}{log.entity_id?` #${log.entity_id}`:''}</span><small>{details(log.details)}</small></div><time>{new Date(log.created_at+'Z').toLocaleString()}</time></article>):<Empty text="No audit events recorded"/>}</div>}

function Users({data,currentUser,mutate}){return <section className="panel admin-table"><div className="panel-heading"><div>Discord accounts & clearance</div><small>{data.length} ACCOUNTS</small></div><div className="admin-row table-head"><span>Identity</span><span>Links</span><span>Economy</span><span>Clearance</span></div>{data.map(row=><div className="admin-row" key={row.id}><div><b>{row.discord_username}</b><small>{row.discord_id==='demo-dispatch'?'Local system account':`Discord ${row.discord_id}`}</small></div><div><span>{row.persona_count} personas</span><small>{row.reformer_uid||row.reforger_uid?'Reforger linked':'Not game-linked'}</small></div><div><b>{money(row.cash_balance)}</b><small>{row.order_count} market orders</small></div><div><select value={row.role} disabled={row.id===currentUser.id} onChange={event=>mutate(`/admin/users/${row.id}`,{method:'PATCH',body:JSON.stringify({role:event.target.value})},`${row.discord_username} role updated.`)}><option>CIVILIAN</option><option>LEO</option><option>EMS</option><option>DISPATCH</option><option>ADMIN</option></select></div></div>)}</section>}

function Personas({rows,mutate,remove}){function edit(row){const alias=prompt('Roleplay alias',row.alias);if(alias===null)return;const driverLicense=prompt('Driver license status',row.driver_license);if(driverLicense===null)return;const firearmLicense=prompt('Firearm license status',row.firearm_license);if(firearmLicense===null)return;mutate(`/admin/characters/${row.id}`,{method:'PATCH',body:JSON.stringify({alias,dob:row.dob,gender:row.gender,driverLicense,firearmLicense})},`${alias} updated.`)}return <section className="panel admin-cards"><div className="panel-heading"><div>Global persona registry</div><small>ALIAS-ONLY IDENTITIES</small></div><div>{rows.map(row=><article key={row.id}><div className="admin-card-icon"><UserCog/></div><div className="grow"><span className="eyebrow">#{row.id} · {row.discord_username}</span><h3>{row.alias}</h3><p>RP DOB {row.dob} · DL {row.driver_license} · Firearms {row.firearm_license}</p></div><button onClick={()=>edit(row)}>Edit</button><button className="danger-button" onClick={()=>remove('characters',row.id,row.alias)}><Trash2/></button></article>)}</div></section>}

function Vehicles({rows,mutate,remove}){function edit(row){const plate=prompt('Plate',row.plate);if(plate===null)return;const model=prompt('Model',row.model);if(model===null)return;const color=prompt('Color',row.color);if(color===null)return;const isStolen=confirm('Mark this vehicle as STOLEN? Choose Cancel for clear.');mutate(`/admin/vehicles/${row.id}`,{method:'PATCH',body:JSON.stringify({plate,model,color,isStolen})},`${plate} updated.`)}return <section className="panel admin-cards"><div className="panel-heading"><div>Vehicle registry</div><small>ALL OWNERS</small></div><div>{rows.map(row=><article key={row.id}><div className="admin-card-icon"><Car/></div><div className="grow"><span className="eyebrow">{row.owner_alias} · {row.discord_username}</span><h3>{row.plate}</h3><p>{row.color} {row.model} · <b className={row.is_stolen?'loss':'gain'}>{row.is_stolen?'STOLEN':'CLEAR'}</b></p></div><button onClick={()=>edit(row)}>Edit</button><button className="danger-button" onClick={()=>remove('vehicles',row.id,row.plate)}><Trash2/></button></article>)}</div></section>}

function Calls({rows,mutate,remove}){function edit(row){const callTitle=prompt('Call title',row.call_title);if(callTitle===null)return;const description=prompt('Description',row.description);if(description===null)return;const status=prompt('Status: OPEN, DISPATCHED, or CLOSED',row.status)?.toUpperCase();if(!status)return;mutate(`/admin/calls/${row.id}`,{method:'PATCH',body:JSON.stringify({callTitle,description,status,callerName:row.caller_name,locationGrid:row.location_grid})},`Call #${row.id} updated.`)}return <section className="panel admin-cards"><div className="panel-heading"><div>Complete call archive</div><small>OPEN & CLOSED</small></div><div>{rows.map(row=><article key={row.id}><div className="admin-card-icon"><PhoneCall/></div><div className="grow"><span className="eyebrow">CALL #{String(row.id).padStart(4,'0')} · {row.location_grid}</span><h3>{row.call_title}</h3><p>{row.description}</p></div><StatusBadge value={row.status}/><button onClick={()=>edit(row)}>Edit</button><button className="danger-button" onClick={()=>remove('calls',row.id,`call #${row.id}`)}><Trash2/></button></article>)}</div></section>}

function Reports({rows,remove}){return <section className="panel admin-cards"><div className="panel-heading"><div>Report archive</div><small>{rows.length} FILES</small></div><div>{rows.map(row=><article key={row.id}><div className="admin-card-icon"><FileText/></div><div className="grow"><span className="eyebrow">{row.report_type} #{row.id} · {row.discord_username}</span><h3>{row.title}</h3><p>{row.narrative.slice(0,180)}{row.narrative.length>180?'…':''}</p></div><button className="danger-button" onClick={()=>remove('reports',row.id,`report #${row.id}`)}><Trash2/></button></article>)}</div></section>}

function Economy({users,orders,mutate}){function balance(row){const cashBalance=prompt(`Virtual cash balance for ${row.discord_username}`,row.cash_balance);if(cashBalance===null)return;mutate(`/admin/economy/${row.id}`,{method:'PATCH',body:JSON.stringify({cashBalance:Number(cashBalance)})},`${row.discord_username} economy balance updated.`)}return <div className="admin-overview-grid"><section className="panel admin-table"><div className="panel-heading"><div>Economy accounts</div><small>VIRTUAL CURRENCY</small></div>{users.map(row=><div className="admin-row economy-row" key={row.id}><div><b>{row.discord_username}</b><small>{row.order_count} orders</small></div><strong>{money(row.cash_balance)}</strong><button onClick={()=>balance(row)}>Adjust balance</button></div>)}</section><section className="panel"><div className="panel-heading"><div>Global order tape</div><small>{orders.length} RECENT</small></div><div className="order-list">{orders.map(order=><div key={order.id}><b className={order.side==='BUY'?'gain':'loss'}>{order.side}</b><strong>{order.quantity} {order.symbol}</strong><span>{money(order.total)}</span><small>{order.discord_username} · {new Date(order.created_at+'Z').toLocaleString()}</small></div>)}</div></section></div>}

function Empty({text}){return <div className="empty"><Activity/><span>{text}</span></div>}
function pretty(value){return value.split('_').map(word=>word[0]+word.slice(1).toLowerCase()).join(' ')}
function details(value){if(!value||Array.isArray(value))return '';return Object.entries(value).slice(0,3).map(([key,val])=>`${key}: ${Array.isArray(val)?val.join(', '):val}`).join(' · ')}
