import { useEffect, useState } from 'react';
import { Building2, Car, CreditCard, FileCheck2, Home, Landmark, RefreshCw, Store, UserRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../api.js';

const money = value => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value || 0);

export default function CivilianHub(){
  const [data,setData]=useState(null),[tab,setTab]=useState('overview'),[message,setMessage]=useState('');
  const [property,setProperty]=useState({propertyName:'',propertyType:'Residence',locationGrid:'',declaredValue:''});
  const [business,setBusiness]=useState({businessName:'',category:'Retail'});
  const [request,setRequest]=useState({requestType:'DMV / License',title:'',details:''});
  const load=()=>api('/civilian/portal').then(setData); useEffect(()=>{load()},[]);
  async function submit(path,body,reset){setMessage('');try{await api(path,{method:'POST',body:JSON.stringify(body)});reset();setMessage('Request saved to your permanent civilian record.');load()}catch(e){setMessage(e.message)}}
  if(!data)return <div className="civilian-loading"><Landmark/><span>Opening resident services…</span></div>;
  return <div>
    <div className="page-heading"><div><p className="eyebrow">SHADOW RP RESIDENT NETWORK</p><h1>Civilian life services</h1><p>Your persistent bank, assets, licenses, businesses, property, and government services in one place.</p></div></div>
    {!data.linked&&<section className="civilian-lock"><Landmark/><div><strong>Permanent banking is waiting for your one-time link</strong><p>Link your Reforger identity to connect your real in-game ATM balance, investing, property, businesses, and civic filings.</p></div><Link className="button primary" to="/linking">Link account</Link></section>}
    {message&&<div className="notice">{message}</div>}
    <div className="civilian-metrics">
      <article><CreditCard/><span>Available cash</span><strong>{data.linked?money(data.account?.cash):'LOCKED'}</strong><small>{data.account?.bankSource==='ATM_BANK_MANAGER'?'Live ATM Bank Manager balance':'Join the game to sync your ATM bank'}</small></article>
      <article><Landmark/><span>Total net worth</span><strong>{data.linked?money(data.account?.netWorth):'—'}</strong><small>Cash plus exchange holdings</small></article>
      <article><UserRound/><span>Roleplay personas</span><strong>{data.characters.length}</strong><small>Alias-only identities</small></article>
      <article><Car/><span>Registered assets</span><strong>{data.vehicles.length+data.properties.length}</strong><small>Vehicles and property</small></article>
    </div>
    <div className="civilian-tabs">{[['overview','Overview'],['bank','Banking'],['property','Property'],['business','Businesses'],['services','Government services']].map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</div>
    {tab==='overview'&&<div className="civilian-grid">
      <section className="panel"><div className="panel-heading"><div>Identity & licenses</div><Link to="/personas">Manage aliases</Link></div><div className="service-list">{data.characters.map(c=><article key={c.id}><UserRound/><div><strong>{c.alias}</strong><span>Driver: {c.driver_license} · Firearms: {c.firearm_license} · RP DOB {c.dob}</span></div></article>)}{!data.characters.length&&<div className="empty">Create a fictional roleplay persona to begin.</div>}</div></section>
      <section className="panel"><div className="panel-heading"><div>Resident activity</div><RefreshCw size={16}/></div><div className="service-list">{data.requests.slice(0,5).map(r=><article key={r.id}><FileCheck2/><div><strong>{r.title}</strong><span>{r.request_type} · {r.status}</span></div></article>)}{!data.requests.length&&<div className="empty">No government service requests yet.</div>}</div></section>
    </div>}
    {tab==='bank'&&<div className="civilian-grid"><section className="panel"><div className="panel-heading"><div>Account ledger</div><small>Bound to your Reforger UID</small></div><div className="ledger">{data.transactions.map(t=><div key={t.id}><span><b>{t.memo}</b><small>{new Date(t.created_at+'Z').toLocaleString()}</small></span><strong className={t.amount>=0?'gain':'loss'}>{t.amount>=0?'+':''}{money(t.amount)}</strong></div>)}{!data.linked&&<div className="empty">Link your account to open persistent banking.</div>}</div></section><section className="panel service-promo"><Landmark/><h2>Shadow Bank + ATM</h2><p>Your website cash is your in-game ATM Bank Manager balance. Stock purchases debit the same bank account and stock sales deposit back into it while you are connected.</p><Link className="button primary" to="/market">Open Shadow Exchange</Link></section></div>}
    {tab==='property'&&<div className="civilian-grid"><section className="panel form-panel"><h2><Home/> Register property</h2><form onSubmit={e=>{e.preventDefault();submit('/civilian/properties',property,()=>setProperty({propertyName:'',propertyType:'Residence',locationGrid:'',declaredValue:''}))}}><label>Property name<input value={property.propertyName} onChange={e=>setProperty({...property,propertyName:e.target.value})} placeholder="Lakeside Apartment" required/></label><div className="two-col"><label>Type<select value={property.propertyType} onChange={e=>setProperty({...property,propertyType:e.target.value})}><option>Residence</option><option>Commercial</option><option>Garage</option><option>Land</option><option>Warehouse</option></select></label><label>Map grid<input value={property.locationGrid} onChange={e=>setProperty({...property,locationGrid:e.target.value})} placeholder="042 067" required/></label></div><label>Declared value<input type="number" min="0" value={property.declaredValue} onChange={e=>setProperty({...property,declaredValue:e.target.value})}/></label><button className="button primary" disabled={!data.linked}>Register asset</button></form></section><section className="panel"><div className="panel-heading">Property portfolio</div><div className="service-list">{data.properties.map(p=><article key={p.id}><Home/><div><strong>{p.property_name}</strong><span>{p.property_type} · Grid {p.location_grid} · {money(p.declared_value)} · {p.status}</span></div></article>)}<div className="empty">Use this registry for homes, garages, land, warehouses, and commercial property.</div></div></section></div>}
    {tab==='business'&&<div className="civilian-grid"><section className="panel form-panel"><h2><Store/> Business registration</h2><form onSubmit={e=>{e.preventDefault();submit('/civilian/businesses',business,()=>setBusiness({businessName:'',category:'Retail'}))}}><label>Roleplay business name<input value={business.businessName} onChange={e=>setBusiness({...business,businessName:e.target.value})} required/></label><label>Industry<select value={business.category} onChange={e=>setBusiness({...business,category:e.target.value})}><option>Retail</option><option>Automotive</option><option>Food & Hospitality</option><option>Security</option><option>Medical</option><option>Transport & Logistics</option><option>Construction</option><option>Media</option><option>Legal Services</option><option>Other</option></select></label><button className="button primary" disabled={!data.linked}>Submit registration</button></form></section><section className="panel"><div className="panel-heading">Owned businesses</div><div className="service-list">{data.businesses.map(b=><article key={b.id}><Building2/><div><strong>{b.business_name}</strong><span>{b.category} · Application {b.status}</span></div></article>)}{!data.businesses.length&&<div className="empty">No business registrations on file.</div>}</div></section></div>}
    {tab==='services'&&<div className="civilian-grid"><section className="panel form-panel"><h2><FileCheck2/> File a service request</h2><form onSubmit={e=>{e.preventDefault();submit('/civilian/requests',request,()=>setRequest({requestType:'DMV / License',title:'',details:''}))}}><label>Department<select value={request.requestType} onChange={e=>setRequest({...request,requestType:e.target.value})}><option>DMV / License</option><option>Firearms Permit</option><option>Vehicle Title</option><option>Property Deed</option><option>Business License</option><option>Court Records</option><option>Public Works</option><option>Insurance Claim</option><option>Employment Services</option><option>Other</option></select></label><label>Subject<input value={request.title} onChange={e=>setRequest({...request,title:e.target.value})} required/></label><label>Request details<textarea rows="5" value={request.details} onChange={e=>setRequest({...request,details:e.target.value})} required/></label><button className="button primary" disabled={!data.linked}>Submit request</button></form></section><section className="panel"><div className="panel-heading">Case tracker</div><div className="service-list">{data.requests.map(r=><article key={r.id}><FileCheck2/><div><strong>{r.title}</strong><span>{r.request_type} · {r.status} · {new Date(r.created_at+'Z').toLocaleDateString()}</span></div></article>)}{!data.requests.length&&<div className="empty">DMV, permits, titles, deeds, insurance, employment, and other services appear here.</div>}</div></section></div>}
  </div>;
}
