import { useEffect, useState } from 'react';
import { Car, Plus, UserRound } from 'lucide-react';
import { api } from '../api.js';

const emptyPerson={firstName:'',lastName:'',dob:'',gender:''};
export default function Personas(){
  const [characters,setCharacters]=useState([]),[vehicles,setVehicles]=useState([]),[person,setPerson]=useState(emptyPerson),[vehicle,setVehicle]=useState({ownerId:'',plate:'',model:'',color:''}),[message,setMessage]=useState('');
  const load=()=>Promise.all([api('/characters'),api('/vehicles')]).then(([people,cars])=>{setCharacters(people.results);setVehicles(cars.results)});useEffect(load,[]);
  async function createPerson(e){e.preventDefault();setMessage('');try{await api('/characters',{method:'POST',body:JSON.stringify(person)});setPerson(emptyPerson);setMessage('Persona created.');load()}catch(err){setMessage(err.message)}}
  async function createVehicle(e){e.preventDefault();setMessage('');try{await api('/vehicles',{method:'POST',body:JSON.stringify(vehicle)});setVehicle({ownerId:'',plate:'',model:'',color:''});setMessage('Vehicle registered.');load()}catch(err){setMessage(err.message)}}
  return <div><div className="page-heading"><div><p className="eyebrow">CIVILIAN PORTAL</p><h1>Roleplay personas</h1><p>Manage identities and vehicle registrations tied to your Discord account.</p></div></div>
    {message&&<div className="notice">{message}</div>}<div className="persona-layout"><section className="panel"><div className="panel-heading"><div>Your personas</div><small>{characters.length} people · {vehicles.length} vehicles</small></div><div className="persona-list">{characters.map(c=><article key={c.id}><div className="unit-avatar"><UserRound/></div><div><strong>{c.first_name} {c.last_name}</strong><span>DOB {c.dob} · DL {c.driver_license} · Firearms {c.firearm_license}</span></div></article>)}{vehicles.map(v=><article key={`v-${v.id}`}><div className="unit-avatar"><Car/></div><div><strong>{v.plate} · {v.model}</strong><span>{v.color} · Registered to {v.owner_name}</span></div></article>)}</div></section>
      <div className="form-stack"><section className="panel form-panel"><h2><Plus/> Create persona</h2><form onSubmit={createPerson}><div className="two-col"><label>First name<input value={person.firstName} onChange={e=>setPerson({...person,firstName:e.target.value})} required/></label><label>Last name<input value={person.lastName} onChange={e=>setPerson({...person,lastName:e.target.value})} required/></label></div><div className="two-col"><label>Date of birth<input type="date" value={person.dob} onChange={e=>setPerson({...person,dob:e.target.value})} required/></label><label>Gender<input value={person.gender} onChange={e=>setPerson({...person,gender:e.target.value})} required/></label></div><button className="button primary">Create persona</button></form></section>
      <section className="panel form-panel"><h2><Car/> Register vehicle</h2><form onSubmit={createVehicle}><label>Owner<select value={vehicle.ownerId} onChange={e=>setVehicle({...vehicle,ownerId:e.target.value})} required><option value="">Choose persona…</option>{characters.map(c=><option value={c.id} key={c.id}>{c.first_name} {c.last_name}</option>)}</select></label><div className="two-col"><label>Plate<input value={vehicle.plate} onChange={e=>setVehicle({...vehicle,plate:e.target.value.toUpperCase()})} required/></label><label>Color<input value={vehicle.color} onChange={e=>setVehicle({...vehicle,color:e.target.value})} required/></label></div><label>Model<input value={vehicle.model} onChange={e=>setVehicle({...vehicle,model:e.target.value})} required/></label><button className="button primary">Register vehicle</button></form></section></div></div>
  </div>;
}
