import { useState } from 'react';
import { FilePlus2 } from 'lucide-react';
import { api } from '../api.js';

export default function Reports(){
  const [form,setForm]=useState({reportType:'INCIDENT',title:'',narrative:'',charges:'',fineAmount:''}),[message,setMessage]=useState('');
  async function submit(e){e.preventDefault();setMessage('');try{const report=await api('/reports',{method:'POST',body:JSON.stringify({...form,charges:form.charges.split(',').map(x=>x.trim()).filter(Boolean)})});setMessage(`Report #${report.id} filed successfully.`);setForm({...form,title:'',narrative:'',charges:'',fineAmount:''})}catch(err){setMessage(err.message)}}
  return <div><div className="page-heading"><div><p className="eyebrow">RECORDS MANAGEMENT</p><h1>New field report</h1><p>File incident, arrest, and citation records.</p></div></div><section className="panel report-panel"><div className="report-aside"><FilePlus2/><h2>Report details</h2><p>Write objective, chronological narratives. All submissions are associated with your authenticated identity.</p></div><form onSubmit={submit}><div className="two-col"><label>Report type<select value={form.reportType} onChange={e=>setForm({...form,reportType:e.target.value})}><option>INCIDENT</option><option>ARREST</option><option>CITATION</option></select></label><label>Fine amount<input type="number" min="0" value={form.fineAmount} onChange={e=>setForm({...form,fineAmount:e.target.value})} placeholder="Optional"/></label></div><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label>Charges <span>(comma separated)</span><input value={form.charges} onChange={e=>setForm({...form,charges:e.target.value})}/></label><label>Narrative<textarea rows="10" value={form.narrative} onChange={e=>setForm({...form,narrative:e.target.value})} required/></label>{message&&<div className="notice">{message}</div>}<button className="button primary">Submit report</button></form></section></div>;
}
